<?php
/**
 * This source file is subject to the GNU General Public License (GNU version 3)
 * It is available through the world-wide-web at this URL:
 * https://www.gnu.org/licenses/gpl-3.0.en.html
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to sales@goivvy.com so we can send you a copy immediately.
 *
 * @component  Goivvyllc_CSS
 * @copyright  Copyright (c) 2025 GOIVVY LLC (https://www.goivvy.com)
 * @license    https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License version 3
 * @author     Goivvy.com <sales@goivvy.com>
 */
?>
<?php
$cut = $block->getData('cssModel');
$mode = $block->getData('mode');
$content = '';
?>
<?php if($content = $cut->getCutCSS($mode)):?>
<style>
<?php echo $content ?>
</style>
<?php endif;?>
